"""change sesion_duration to _sesion_duration and add _days_in_week
    and add _days_in_week column to plans table

Revision ID: 1dd4cb7a17a7
Revises: 6981ae2f9dd7
Create Date: 2024-12-24 23:37:52.843684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dd4cb7a17a7'
down_revision = '6981ae2f9dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_sesion_duration', sa.Integer(), nullable=True))
        batch_op.drop_column('sesion_duration')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_days_in_week', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('_days_in_week')

    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sesion_duration', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('_sesion_duration')

    # ### end Alembic commands ###
