""" change the names of the columns in the records and workout_sessions tables

Revision ID: 478929920e74
Revises: 8ab4c0c326da
Create Date: 2024-12-25 09:26:41.277850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '478929920e74'
down_revision = '8ab4c0c326da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_sets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('_reps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('_rest', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('_weight_lifted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('_user_weight', sa.Float(), nullable=False))
        batch_op.drop_column('sets')
        batch_op.drop_column('reps')
        batch_op.drop_column('rest')
        batch_op.drop_column('weight_lifted')
        batch_op.drop_column('user_weight')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_sets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('_reps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('_rest', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('_weight_lifted', sa.Float(), nullable=True))
        batch_op.drop_column('sets')
        batch_op.drop_column('rest')
        batch_op.drop_column('weight_lifted')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('weight_lifted', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rest', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('sets', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('_weight_lifted')
        batch_op.drop_column('_rest')
        batch_op.drop_column('_reps')
        batch_op.drop_column('_sets')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_weight', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('weight_lifted', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rest', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('reps', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sets', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('_user_weight')
        batch_op.drop_column('_weight_lifted')
        batch_op.drop_column('_rest')
        batch_op.drop_column('_reps')
        batch_op.drop_column('_sets')

    # ### end Alembic commands ###
