"""change the relationship between custom_exercises and workout_session to one-many, each workout_session inludes one custom_exercise id as ForeignKey

Revision ID: 4a037cb10f25
Revises: e52024ec93dd
Create Date: 2025-01-22 13:25:57.112940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a037cb10f25'
down_revision = 'e52024ec93dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sessions_custom_exercises')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_exercise_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('workout_sessions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'custom_exercises', ['custom_exercise_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('workout_sessions_ibfk_2', 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('custom_exercise_id')

    op.create_table('workout_sessions_custom_exercises',
    sa.Column('workout_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_exercise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['custom_exercise_id'], ['custom_exercises.id'], name='workout_sessions_custom_exercises_ibfk_2'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], name='workout_sessions_custom_exercises_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_session_id', 'custom_exercise_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
