"""ensures the when a user or a role is deleted, the entry in the table user_roles is also deleted

Revision ID: 69ac818bb861
Revises: 874ef2112be6
Create Date: 2025-01-07 23:25:30.592179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ac818bb861'
down_revision = '874ef2112be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('user_roles_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_roles_ibfk_2', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###
