"""change the relationship between exercises and workout_session to one-many, each workout_session inludes one exercise id as ForeignKey

Revision ID: e52024ec93dd
Revises: 90bf816f4a49
Create Date: 2025-01-22 00:03:23.977422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e52024ec93dd'
down_revision = '90bf816f4a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sessions_exercises')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exercise_id')

    op.create_table('workout_sessions_exercises',
    sa.Column('workout_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='workout_sessions_exercises_ibfk_2'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], name='workout_sessions_exercises_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_session_id', 'exercise_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
