"""empty message

Revision ID: f83ed54aea94
Revises: 69ac818bb861
Create Date: 2025-01-11 01:19:27.576195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83ed54aea94'
down_revision = '69ac818bb861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('user_role_unique')
        batch_op.drop_constraint('user_roles_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_roles_ibfk_2', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('user_role_unique', ['user_id', 'role_id'], unique=True)

    # ### end Alembic commands ###
